export var FETCH_REQUIST_TICKETS="FETCH_REQUIST_TICKETS"
export var FETCH_SUCCESS_TICKETS="FETCH_SUCCESS_TICKETS"
export var FETCH_FAILED_TICKETS="FETCH_FAILED_TICKETS"
export var FETCH_SUCCESS_ALL="FETCH_SUCCESS_ALL"